### ISSUE TITLE
Mismatch in the paper - Large Kernel Mixer

### ISSUE THREAD

**Issue by amitbar05** [Aitical/CFSR#2]
In the paper, there is a mismatch between the architecture layout of the Large Kernel Mixer:
![image](https://github.com/Aitical/CFSR/assets/13821119/492bd624-611b-4175-9516-edddb310cdd3)

And the math formulation:
![image](https://github.com/Aitical/CFSR/assets/13821119/585db4f1-4b63-46b6-aee1-16e4a4bd331e)

Where in the first image, we first mix the channels, and then apply large kernel convolution, (ang again channel mixing on the output at the end).
And in the formulation, the large depth-wise convolution occurs and then the channel mixing (with 1x1).
What architecture did you use for the actual implementation?

**Comment by Aitical** [comment]
Thank you for your attention. We apologize for the previous error. We have corrected and improved the manuscript in revision. The final version will be updated soon.
