### ISSUE TITLE
整体代码

### ISSUE THREAD

**Issue by wjkbigface** [Aitical/CFSR#7]
你好 剩下的代码什么时候发呀

**Comment by Aitical** [comment]
感谢您对我们工作的关注！

我理解您说的“剩下的代码”是指完整的项目实现，因为我的训练和测试过程都是基于basicsr项目的，所以复用部分这里没有上传。
请您参考https://github.com/XPixelGroup/BasicSR项目，clone到本地后将本项目的代码移动到basicsr中安装就可以训练和测试了。
